export const PAGES = {
  HOME_PAGE: "",
  PROJECTS: "/projects",
  SEARCH: "/search",
  MESSAGES: "/message",
  GROUP: "/groups",
  NOTIFY: "/notify",
  SETTING: "/settings",
  MY_PROJECT: "/my-projects",
  SIGN_UP: "/sign-up",
  FIND_ACCOUNT: "/find-account",
  OTP: "/otp",
  REST_PASSWORD: "/reset-password",
  POST: "/post",
  PROFILE: "/me",
};
