export const LIST_CHAT = [
  {
    key: 1,
    avatar: "",
    name: "Alene",
    lastMess: "Technical Department",
    time: "2h ago",
    notify: 2,
    status: 1,
  },
  {
    key: 2,
    avatar: "",
    name: "Keeft",
    lastMess: "Support Executive",
    time: "1:20 AM",
    notify: 3,
    status: 0,
  },
  {
    key: 3,
    avatar: "",
    name: "Lazaro",
    lastMess: "Resource Investigator",
    time: "Yesterday",
    notify: 1,
    status: 1,
  },
  {
    key: 1,
    avatar: "",
    name: "Hazle",
    lastMess: "Team worker",
    time: "4/25/2021",
    notify: 0,
    status: 1,
  },
  {
    key: 1,
    avatar: "",
    name: "Herman Essertg",
    lastMess: "Co-ordinator",
    time: "4/25/2021",
    notify: 0,
    status: 0,
  },
  {
    key: 1,
    avatar: "",
    name: "Alene",
    lastMess: "Technical Department",
    time: "2h ago",
    notify: 2,
    status: 1,
  },
  {
    key: 2,
    avatar: "",
    name: "Keeft",
    lastMess: "Support Executive",
    time: "1:20 AM",
    notify: 3,
    status: 0,
  },
  {
    key: 3,
    avatar: "",
    name: "Lazaro",
    lastMess: "Resource Investigator",
    time: "Yesterday",
    notify: 1,
    status: 1,
  },
  {
    key: 1,
    avatar: "",
    name: "Hazle",
    lastMess: "Team worker",
    time: "4/25/2021",
    notify: 0,
    status: 1,
  },
  {
    key: 1,
    avatar: "",
    name: "Herman Essertg",
    lastMess: "Co-ordinator",
    time: "4/25/2021",
    notify: 0,
    status: 0,
  },
  {
    key: 1,
    avatar: "",
    name: "Alene",
    lastMess: "Technical Department",
    time: "2h ago",
    notify: 2,
    status: 1,
  },
  {
    key: 2,
    avatar: "",
    name: "Keeft",
    lastMess: "Support Executive",
    time: "1:20 AM",
    notify: 3,
    status: 0,
  },
  {
    key: 3,
    avatar: "",
    name: "Lazaro",
    lastMess: "Resource Investigator",
    time: "Yesterday",
    notify: 1,
    status: 1,
  },
  {
    key: 1,
    avatar: "",
    name: "Hazle",
    lastMess: "Team worker",
    time: "4/25/2021",
    notify: 0,
    status: 1,
  },
  {
    key: 1,
    avatar: "",
    name: "Herman Essertg",
    lastMess: "Co-ordinator",
    time: "4/25/2021",
    notify: 0,
    status: 0,
  },
];
